apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: release-manifest
  annotations:
    pipelinesascode.tekton.dev/task-1: "[git-clone]"
    pipelinesascode.tekton.dev/task-2: "[git-cli]"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/tags/*]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  workspaces:
  - name: repos-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

  pipelineSpec:
    workspaces:
    - name: repos-workspace
    tasks:
      - name: fetch-rh1-release-manifest-repo-source
        taskRef:
          name: git-clone
        params:
        - name: url
          value: "{{ repo_url }}"
        - name: revision
          value: "{{ git_tag }}"
        - name: verbose
          value: "true"
        - name: subdirectory
          value: "rh1-release-manifest"
        workspaces:
        - name: output
          workspace: repos-workspace

      - name: check-for-release-file
        runAfter:
        - fetch-rh1-release-manifest-repo-source
        workspaces:
          - name: repos-workspace
        taskSpec:
          workspaces:
          - name: repos-workspace
          steps:
          - name: check-for-release-file
            workingDir: $(workspaces.repos-workspace.path)/rh1-release-manifest/releases/
            image: registry.redhat.io/openshift4/ose-tools-rhel9
            script: |
              #!/usr/bin/env sh
              set -eu
              echo "Looking for release file release-{{ git_tag }}.yml"
              if [[ -f "release-{{ git_tag }}.yml" ]]; then
                echo "Release file found"
                exit 0
              else
                echo "Release file missing"
                exit 1
              fi

      - name: fetch-rh1-custom-collection-repo-source
        runAfter:
        - check-for-release-file
        taskRef:
          name: git-clone
        params:
        - name: url
          value: "https://github.com/djdanielsson/rh1-custom-collection.git"
        - name: revision
          value: "main"
        - name: verbose
          value: "true"
        - name: subdirectory
          value: "rh1-custom-collection"
        workspaces:
        - name: output
          workspace: repos-workspace

      - name: fetch-rh1-automation-playbooks-repo-source
        runAfter:
        - fetch-rh1-custom-collection-repo-source
        taskRef:
          name: git-clone
        params:
        - name: url
          value: "https://github.com/djdanielsson/rh1-automation-playbooks.git"
        - name: revision
          value: "main"
        - name: verbose
          value: "true"
        - name: subdirectory
          value: "rh1-automation-playbooks"
        workspaces:
        - name: output
          workspace: repos-workspace

      - name: fetch-rh1-ee-repo-source
        runAfter:
        - fetch-rh1-automation-playbooks-repo-source
        taskRef:
          name: git-clone
        params:
        - name: url
          value: "https://github.com/djdanielsson/rh1-ee.git"
        - name: revision
          value: "main"
        - name: verbose
          value: "true"
        - name: subdirectory
          value: "rh1-ee"
        workspaces:
        - name: output
          workspace: repos-workspace

      - name: fetch-rh1-aap-config-as-code-repo-source
        runAfter:
        - fetch-rh1-ee-repo-source
        taskRef:
          name: git-clone
        params:
        - name: url
          value: "https://github.com/djdanielsson/rh1-aap-config-as-code.git"
        - name: revision
          value: "main"
        - name: verbose
          value: "true"
        - name: subdirectory
          value: "rh1-aap-config-as-code"
        workspaces:
        - name: output
          workspace: repos-workspace

      - name: tag-and-push-rh1-automation-playbooks-repo
        runAfter:
        - fetch-rh1-aap-config-as-code-repo-source
        taskRef:
          name: git-cli
        params:
        - name: VERBOSE
          value: "true"
        - name: GIT_USER_NAME
          value: "release-bot"
        - name: GIT_SCRIPT
          value: |
            cd rh1-automation-playbooks
            git tag -f {{ git_tag }}
            git push origin {{ git_tag }} --force
        workspaces:
          - name: source
            workspace: repos-workspace

      # - name: tag-and-push-rh1-custom-collection-playbooks-repo
      #   runAfter:
      #   - fetch-rh1-automation-playbooks-repo-source
      #   taskRef:
      #     name: git-cli
      #   params:
      #   - name: verbose
      #     value: "true"
      #   - name: git_user_name
      #     value: "release-bot"
      #   - name: git_script
      #     value: |
      #       git tag -a {{ git_tag }} -m "Release tag for {{ git_tag }}"

      # - name: tag-and-push-rh1-ee-repo
      #   runAfter:
      #   - fetch-rh1-custom-collection-repo-source
      #   taskRef:
      #     name: git-cli
      #   params:
      #   - name: verbose
      #     value: "true"
      #   - name: git_user_name
      #     value: "release-bot"
      #   - name: git_script
      #     value: |
      #       git tag -a {{ git_tag }} -m "Release tag for {{ git_tag }}"

      # - name: tag-and-push-rh1-aap-config-as-code-repo
      #   runAfter:
      #   - fetch-rh1-ee-repo-source
      #   taskRef:
      #     name: git-cli
      #   params:
      #   - name: verbose
      #     value: "true"
      #   - name: git_user_name
      #     value: "release-bot"
      #   - name: git_script
      #     value: |
      #       git tag -a {{ git_tag }} -m "Release tag for {{ git_tag }}"